# Generated by Django 4.2 on 2024-02-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.CharField(default='https://5b0988e595225.cdn.sohucs.com/images/20191217/110701b9a43b413883c5c104d818dd91.jpeg', max_length=500),
        ),
    ]
