# Generated by Django 4.2 on 2024-02-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_manager', '0002_article_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.CharField(default='https://img2.baidu.com/it/u=1337941324,845441152&fm=253&fmt=auto&app=138&f=JPEG?w=640&h=452', max_length=500),
        ),
    ]
