# Generated by Django 4.2 on 2024-02-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0002_datalinker_avatar_url_datalinker_self_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalinker',
            name='avatar_url',
            field=models.CharField(default='https://5b0988e595225.cdn.sohucs.com/images/20191217/110701b9a43b413883c5c104d818dd91.jpeg', max_length=1000),
        ),
    ]
